/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoPositivoRouteImport } from './routes/fo-positivo'
import { Route as FoNegativoRouteImport } from './routes/fo-negativo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'

const FoPositivoRoute = FoPositivoRouteImport.update({
  id: '/fo-positivo',
  path: '/fo-positivo',
  getParentRoute: () => rootRouteImport,
} as any)
const FoNegativoRoute = FoNegativoRouteImport.update({
  id: '/fo-negativo',
  path: '/fo-negativo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard': typeof DashboardRoute
  '/fo-negativo': typeof FoNegativoRoute
  '/fo-positivo': typeof FoPositivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard': typeof DashboardRoute
  '/fo-negativo': typeof FoNegativoRoute
  '/fo-positivo': typeof FoPositivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRoute
  '/dashboard': typeof DashboardRoute
  '/fo-negativo': typeof FoNegativoRoute
  '/fo-positivo': typeof FoPositivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alunos' | '/dashboard' | '/fo-negativo' | '/fo-positivo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alunos' | '/dashboard' | '/fo-negativo' | '/fo-positivo'
  id:
    | '__root__'
    | '/'
    | '/alunos'
    | '/dashboard'
    | '/fo-negativo'
    | '/fo-positivo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRoute
  DashboardRoute: typeof DashboardRoute
  FoNegativoRoute: typeof FoNegativoRoute
  FoPositivoRoute: typeof FoPositivoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fo-positivo': {
      id: '/fo-positivo'
      path: '/fo-positivo'
      fullPath: '/fo-positivo'
      preLoaderRoute: typeof FoPositivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fo-negativo': {
      id: '/fo-negativo'
      path: '/fo-negativo'
      fullPath: '/fo-negativo'
      preLoaderRoute: typeof FoNegativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRoute,
  DashboardRoute: DashboardRoute,
  FoNegativoRoute: FoNegativoRoute,
  FoPositivoRoute: FoPositivoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
